### ISSUE TITLE
Contributing: the license

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-cloud-client-example#32]
I believe this example should follow inbound - outbound license . We shall add to the Readme a new section License and contributions. 

Good example is in Mbed OS repository:

```
### License and contributions

The software is provided under Apache-2.0 license. Contributions to this project are accepted under the same license. Please see contributing.md for more info.

This project contains code from other projects. The original license text is included in those source files. They must comply with our license guide.
```

**Comment by 0xc0170** [comment]
Can this be fixed? Use https://github.com/ARMmbed/mbed-os-example-blinky as an example (see Readme section and license/contributing md files)

**Comment by JanneKiiskila** [comment]
It's quite not as simple as that, due to the release model we were asked to use. We can't simply just merge stuff, as these repos are more just like the "outgoing" repo. The development is in the internal repos and we do code drops to the external, public repos as part of release. That will then loose the external contribution commits, their history & author info, which is not good.

**Comment by JanneKiiskila** [comment]
Next release will have CONTRIBUTE.md files with relevant details and PRs will get templates for answering a few questions.

**Comment by JanneKiiskila** [comment]
This is now covered via release 4.3.0.
