### ISSUE TITLE
Are there plans to update with mbed os 5.15.3 or wait for 6.0.0?

### ISSUE THREAD

**Issue by dannywahlquist** [ARMmbed/mbed-cloud-client-example#69]

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-4213

**Comment by teetak01** [comment]
HI @dannywahlquist 

We update this application along side https://github.com/ARMmbed/mbed-cloud-client as integrated package. We plan to update to future patch release when we are ready to make next Device Management Client release. Thus we do not do just lib-updates in this repository outside of normal release cycles.

Now, Mbed OS 5.15.2 introduced backwards compatibility breakage for PSA APIs (and a bug in that implementation too), thus the next version we can use will be Mbed OS 5.15.4. We also need to fix the PSA API compatiblity for the client library at the same time.

Otherwise there is no issue with current patch versions. https://github.com/ARMmbed/mbed-cloud-client is already using Mbed OS 5.15.3 (as there is no actual PSA targets in use).

**Comment by spanalytics** [comment]
Thanks!

**Comment by teetak01** [comment]
Closing as resolved.
